name: karpel_food_delivery
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  otp_pin_field: ^1.2.0+2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.8
  google_maps_flutter: ^2.3.1
  custom_map_markers: ^0.0.2+1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  url_launcher: ^6.3.1
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  intl: ^0.18.0
  shimmer: ^3.0.0
  geolocator: ^10.1.0
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/app_logo.png"